//! Render the mediamtx config and lay down the cert/key/config files.
//!
//! mediamtx serves WHIP (ingest) + WHEP (egress) over HTTPS on one port. We turn
//! off every other protocol. Audio is Opus, one publisher per path, many WHEP
//! subscribers — exactly the one-to-many interpretation shape.
//!
//! ⚠️ mediamtx's config schema (esp. the auth block) shifts between versions.
//! This targets mediamtx v1.x. Confirm against the bundled binary at rig test
//! and adjust [`MediamtxConfig::render`] if keys differ.

use anyhow::Result;
use std::path::{Path, PathBuf};

pub struct MediamtxConfig {
    /// HTTPS port for WHIP/WHEP/WebRTC (e.g. 8889).
    pub https_port: u16,
    /// Absolute path to the TLS cert (PEM/fullchain).
    pub cert_path: String,
    /// Absolute path to the TLS private key (PEM).
    pub key_path: String,
    /// When set, WHIP publishing requires user `publish` + this password
    /// (the session secret). WHEP reading stays open on the LAN. None = open
    /// publish too (only for the first POC; harden before real use).
    pub publish_secret: Option<String>,
}

impl MediamtxConfig {
    pub fn render(&self) -> String {
        let auth = match &self.publish_secret {
            Some(secret) => format!(
                "\
authInternalUsers:
  - user: any
    permissions:
      - action: read
  - user: publish
    pass: {secret}
    permissions:
      - action: publish
",
            ),
            None => String::from(
                "\
# POC: open publish + read on the LAN. Harden by setting publish_secret.
authInternalUsers:
  - user: any
    permissions:
      - action: read
      - action: publish
",
            ),
        };

        format!(
            "\
# Generated by sundaytranslate-relay — do not edit by hand.
logLevel: info
logDestinations: [stdout]

# Only WebRTC (WHIP ingest + WHEP egress); everything else off.
rtsp: no
rtmp: no
hls: no
srt: no

webrtc: yes
webrtcAddress: :{port}
webrtcEncryption: yes
webrtcServerCert: {cert}
webrtcServerKey: {key}
# Local control API (status/metrics) on loopback only.
api: yes
apiAddress: 127.0.0.1:9997

{auth}
# Any path is publishable/readable; the web app picks unique stream names
# (`<sessionId>_<kind>-<locale>`), so paths are created on demand.
pathDefaults:
  source: publisher
paths:
  all_others:
",
            port = self.https_port,
            cert = self.cert_path,
            key = self.key_path,
            auth = auth,
        )
    }
}

/// Lay the cert, key and config into `data_dir`; return their paths.
pub async fn write_files(
    data_dir: &Path,
    cert_pem: &str,
    key_pem: &str,
    cfg: &MediamtxConfig,
) -> Result<PathBuf> {
    tokio::fs::create_dir_all(data_dir).await?;
    let cert_path = Path::new(&cfg.cert_path);
    let key_path = Path::new(&cfg.key_path);
    tokio::fs::write(cert_path, cert_pem).await?;
    tokio::fs::write(key_path, key_pem).await?;
    let config_path = data_dir.join("mediamtx.yml");
    tokio::fs::write(&config_path, cfg.render()).await?;
    Ok(config_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg(secret: Option<&str>) -> MediamtxConfig {
        MediamtxConfig {
            https_port: 8889,
            cert_path: "/d/cert.pem".into(),
            key_path: "/d/key.pem".into(),
            publish_secret: secret.map(str::to_string),
        }
    }

    #[test]
    fn render_wires_webrtc_https_and_disables_others() {
        let y = cfg(Some("sek")).render();
        assert!(y.contains("webrtc: yes"));
        assert!(y.contains("webrtcAddress: :8889"));
        assert!(y.contains("webrtcEncryption: yes"));
        assert!(y.contains("webrtcServerCert: /d/cert.pem"));
        assert!(y.contains("webrtcServerKey: /d/key.pem"));
        assert!(y.contains("rtsp: no") && y.contains("rtmp: no") && y.contains("hls: no"));
    }

    #[test]
    fn with_secret_requires_publish_auth() {
        let y = cfg(Some("topsecret")).render();
        assert!(y.contains("user: publish"));
        assert!(y.contains("pass: topsecret"));
    }

    #[test]
    fn without_secret_publish_is_open() {
        let y = cfg(None).render();
        assert!(!y.contains("pass:"));
        assert!(y.contains("action: publish"));
    }
}
